### ISSUE TITLE
running issue with collections package

### ISSUE THREAD

**Issue by immorBen** [angelosalatino/cso-classifier#10]
When running "test.test_classifier_single_paper()", 
```python
>>> import cso_classifier as test
>>> test.test_classifier_single_paper()
```
got the following messages:
> De-anonymizing Social Networks
> Operators of online social networks are increasingly sharing potentially sensitive information about users and their relationships with advertisers, application developers, and data-mining researchers. Privacy is typically protected by anonymization, i.e., removing names, addresses, etc. We present a framework for analyzing privacy and anonymity in social networks and develop a new re-identification algorithm targeting anonymized social-network graphs. To demonstrate its effectiveness on real-world networks, we show that a third of the users who can be verified to have accounts on both Twitter, a popular microblogging service, and Flickr, an online photo-sharing site, can be re-identified in the anonymous Twitter graph with only a 12% error rate. Our de-anonymization algorithm is based purely on the network topology, does not require creation of a large number of dummy "sybil" nodes, is robust to noise and all existing defenses, and works even when the overlap between the target network and the adversary's auxiliary information is small.
> data mining, data privacy, graph theory, social networking (online)
> Computer Science Ontology loaded.
> Model loaded.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "[my-personal-path]python3.10/site-packages/cso_classifier/test.py", line 35, in test_classifier_single_paper
>     result = cso_classifier.run(paper)
>   File "[my-personal-path]/python3.10/site-packages/cso_classifier/classifier.py", line 80, in run
>     self.model = MODEL(use_full_model=self.use_full_model, silent = self.silent)
>   File "[my-personal-path]/python3.10/site-packages/cso_classifier/model.py", line 27, in \__init\__
>     self.load_models()
>   File "[my-personal-path]/python3.10/site-packages/cso_classifier/model.py", line 35, in load\_models
>     self.\__load\_word2vec\_model()
>   File "[my-personal-path]python3.10/site-packages/cso_classifier/model.py", line 167, in \__load\_word2vec\_model
>     self.full_model = pickle.load(open(self.config.get_model_pickle_path(), "rb"))
>   File "[my-personal-path]/python3.10/site-packages/gensim/\__init\__.py", line 5, in <module>
>     from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
>   File "[my-personal-path]/python3.10/site-packages/gensim/corpora/\__init\__.py", line 12, in <module>
>     from .dictionary import Dictionary  # noqa:F401
>   File "[my-personal-path]/python3.10/site-packages/gensim/corpora/dictionary.py", line 11, in <module>
>     from collections import Mapping, defaultdict
> ImportError: cannot import name 'Mapping' from 'collections' ([my-personal-path]lib/python3.10/collections/\__init\__.py)

and "from collections.abc import Mapping" works well. @angelosalatino  

If changing `File "[my-personal-path]lib/python3.10/site-packages/gensim/corpora/dictionary.py"`, modify the import as "from collections.abc import Mapping", another importing error occurred: 
> ImportError: cannot import name 'Iterable' from 'collections' ([my-personal-path]/lib/python3.10/collections/\__init\__.py)

`gensim/models/fasttext.py` also uses "Iterable"...

details about my environment
os: ubuntu 18.04.6 LTS
versions:
- conda: 4.12.0
- python: 3.10.4
- cso-classifier: 3.0
- cso ontology: 3.3

**Comment by immorBen** [comment]
A somewhat similar issue happened in [Azure related issues](https://github.com/Azure/azure-cli/issues/20444#issuecomment-1009648464), they suggested modifying "import Mapping/Iterable from collections.abc" in related scripts.

**Comment by immorBen** [comment]
As reflected somewhere else, this import error is along with python 3.10. Re-install with python 3.8.8 can figure out this problem.
