### ISSUE TITLE
Error while generating package metadata/metadata-generation-failed

### ISSUE THREAD

**Issue by DudeitsHp** [angelosalatino/cso-classifier#15]
>pip install cso_classifier
Collecting cso_classifier
  Using cached cso_classifier-3.1-py3-none-any.whl (44 kB)
Collecting gensim==3.8.3 (from cso_classifier)
  Using cached gensim-3.8.3.tar.gz (23.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      running dist_info
      creating C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-modern-metadata-8wigd2ba\gensim.egg-info
      writing C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-modern-metadata-8wigd2ba\gensim.egg-info\PKG-INFO
      writing dependency_links to C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-modern-metadata-8wigd2ba\gensim.egg-info\dependency_links.txt
      writing requirements to C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-modern-metadata-8wigd2ba\gensim.egg-info\requires.txt
      writing top-level names to C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-modern-metadata-8wigd2ba\gensim.egg-info\top_level.txt
      writing manifest file 'C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-modern-metadata-8wigd2ba\gensim.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "d:\HP\skillmatch\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "d:\HP\skillmatch\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "d:\HP\skillmatch\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 367, in <module>
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 99, in run
          self.egg_info.run()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 314, in run
          self.find_sources()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 322, in find_sources
          mm.run()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\command\sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\Hari Prasath M S\AppData\Local\Temp\pip-build-env-5gkugv0y\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 111, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

//////////////
Python 3.11.0

**Comment by angelosalatino** [comment]
Hi,

I have never tested with Python 3.11.

Can you try 3.8? or 3.7?
