### ISSUE TITLE
error in setup of cso classifier

### ISSUE THREAD

**Issue by AsmaKhatoon123** [angelosalatino/cso-classifier#17]
hello there

Following the mentioned steps, we have got this error 

"python setup.py egg_info did not run successfully.
  exit code: 1

[8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\asmas\cso-classifier\setup.py", line 5, in <module>
      long_description = fh.read()
    File "C:\Users\asmas\anaconda3\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 38260: character maps to <undefined>
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details."

can you help in this

**Comment by angelosalatino** [comment]
hi @AsmaKhatoon123 which version of python are you using?

**Comment by AsmaKhatoon123** [comment]
It's 3.11

**Comment by angelosalatino** [comment]
Can you try either 3.7 or 3.8? 

Currently it does not support versions from 3.10 onwards

**Comment by AsmaKhatoon123** [comment]
The older versions are in security fix phases, download page is redirecting
to t

**Comment by AsmaKhatoon123** [comment]
The older versions are in security fix phases, download page is redirecting
to the newer versions of python.

**Comment by angelosalatino** [comment]
Have you tried here: https://www.python.org/downloads/release/python-3717/

**Comment by AsmaKhatoon123** [comment]
I have tried using python 3.8 in a virtual environment but getting the same
issue.

**Comment by angelosalatino** [comment]
Very strange. I will have someone look into this. 

Can you give me more details so to reproduce the error?
I am assuming you are using windows OS.

Are you installing the github version or the pipy version?

Which your current python version?

Can I also ask you to run a test for me? Can you download and try to install the version on github (instead of pipy)? Please comment line 4 and 5 of setup.py before installing it.
This seems a silly coded error that may come from the readme file

Thank you

**Comment by AsmaKhatoon123** [comment]
I have tried all the instructions, but the same error prompts every time. i
need to classify the topics from the abstract and the title, can i do it
using  "https://cso.kmi.open.ac.uk/classify/" do they have the same effect
as the CSO-classifier?

**Comment by angelosalatino** [comment]
Yes, they are the same code. Just exposed online.

It depends how many paper you have to classify.

if it is in the range of 10/20 then yes. If it happens to be more than that, I would encorage to fix the python library.

If you comment line 4 and 5 of setup.py before installing it, what error do you get? 
Sorry, but without a clear error statement it is very hard to troubleshoot.

Best

**Comment by Ausafhaqqani** [comment]
Hi i am facing the same problem as well what is the best solution to this

**Comment by Ausafhaqqani** [comment]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ah79956\LDA\cso-classifier\setup.py", line 5, in <module>
          long_description = fh.read()
        File "C:\Users\ah79956\anaconda\envs\lda\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 48030: character maps to <undefined>    
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ah79956\LDA\cso-classifier\setup.py", line 5, in <module>
          long_description = fh.read()
        File "C:\Users\ah79956\anaconda\envs\lda\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 48030: character maps to <undefined>    
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ah79956\LDA\cso-classifier\setup.py", line 5, in <module>
          long_description = fh.read()
        File "C:\Users\ah79956\anaconda\envs\lda\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 48030: character maps to <undefined>    
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by angelosalatino** [comment]
Hi Can you give more details on the verison of python you are using?

Also which OS?

**Comment by Ausafhaqqani** [comment]
Python version 3.8 OS is Windows 11 on x64 arch

**Comment by angelosalatino** [comment]
Did you try via Pipy or you used this version on Github?

Please note the version on github is ahead of Pipy.

**Comment by Ausafhaqqani** [comment]
Sorry I didn’t understand your question I should use pipy instead of pip and use for the git clone also use pipy ./cso-classifier

**Comment by angelosalatino** [comment]
Not a problem. Did you install the version on Pipy or you installed the version of Github?

Actually, the main question is which version of cso-classifier were you trying to install?

**Comment by Ausafhaqqani** [comment]
i installed the version on pipy

**Comment by Ausafhaqqani** [comment]
Collecting cso-classifier
  Using cached cso_classifier-3.1-py3-none-any.whl.metadata (43 kB) its this version

**Comment by Ausafhaqqani** [comment]
hint: See above for details.

(lda) C:\Users\ah79956\LDA>pip install ./cso-classifier
Processing c:\users\ah79956\lda\cso-classifier
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ah79956\LDA\cso-classifier\setup.py", line 5, in <module>
          long_description = fh.read()
        File "C:\Users\ah79956\anaconda\envs\lda\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 48030: character maps to <undefined>    
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 

the above is the issue with installing on pip install for github clone

**Comment by angelosalatino** [comment]
Can you try to install the version on Github, following the instructions here: https://github.com/angelosalatino/cso-classifier?tab=readme-ov-file#installation-using-github?

Unfortunately, I have never encoutered such a issue, and I am trying to isolate the source of the problem.

Thanks

**Comment by Ausafhaqqani** [comment]
That is what i have followed and that is the error i get as stated above, do i install the tar.gz ?

**Comment by Ausafhaqqani** [comment]
File "C:\Users\ah79956\anaconda\envs\lda\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 47276: character maps to <undefined>
      [end of output] that is the error if it helps to resolve it

**Comment by angelosalatino** [comment]
Ok. It is the encoding.

Can you replace line 4 in setup.py with the following and try again.
```with open("README.md", "r", encoding='utf-8') as fh:```
